on: [push]

jobs:
  create-class-diagram:
    runs-on: ubuntu-latest
    name: Create class diagram
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create class diagram
        id: create-class-diagram
        uses: smeghead/php-class-diagram-gh-action@v0
        with:
          src-directory: src
          output-path: diagram.png

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: diagram.png
          path: diagram.png
          retention-days: 5

      - name: Get the output time
        run: echo "The time was ${{ steps.create-class-diagram.outputs.time }}"
