on: [push]

jobs:
  create-class-diagram:
    runs-on: ubuntu-latest
    name: Create class diagram
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create class diagram
        id: create-class-diagram
        uses: smeghead/php-class-diagram-gh-action@v0
        with:
          target-path: src
          output-path: class-diagram.png
          options: --disable-class-properties --disable-class-methods

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Class_Diagram
          path: class-diagram.png
          retention-days: 5
